### ISSUE TITLE
Ohio well log observation service URLs don't work

### ISSUE THREAD

**Issue by smrazgs** [ngds/metadata-issues#28]
http://www.dnr.state.oh.us/geosurvey/ogcim/petrol/dlg/tabid/7775/Default.aspx  is dead, goes to dnr home page.

this is from WFS at 
http://geothermal.isgs.illinois.edu/ArcGIS/services/aasggeothermal/OHWellLogs/MapServer/WFSServer?request=GetCapabilities&service=WFS

metadata record at http://catalog.usgin.org/geoportal/rest/document?id=%7B60A3F2DB-B3C5-4607-B79E-88FC8DE97D4C%7D

**Comment by ccaudill** [comment]
Current task at http://task.usgin.org/task/2247

**Comment by Lbookman** [comment]
updated the redirects and sent it to Melony. waiting to hear back.

**Comment by Lbookman** [comment]
I couldn't redirect the loguri to that site because that would cause a lot of duplicates so I redirected them to xml and added  https://gis.ohiodnr.gov/Website/DOG/WellSummaryCard.asp?api=34005240480000 to ScannedFileURL.

**Comment by Lbookman** [comment]
service up and corrected in the repo site.
