### ISSUE TITLE
OR Thermal Springs service WMS not enabled

### ISSUE THREAD

**Issue by ccaudill** [ngds/metadata-issues#50]
http://repository.stategeothermaldata.org/repository/resource/cc54f15894222c91e71e4530dc01e747/

Fixed URL, but OR doesn't have the WMS turned on for this service (http://www.oregongeology.org/arcgis/rest/services/Public/ORThermalSprings/MapServer)

Sent Clark at OR an email today

**Comment by Lbookman** [comment]
WMS works but missing metadata

**Comment by Lbookman** [comment]
WMS is turned on.
