### ISSUE TITLE
Kansas moving geothermal services 

### ISSUE THREAD

**Issue by Lbookman** [ngds/metadata-issues#52]
The existing addresses will still work for some time, but here are the new ones:

http://services.kgs.ku.edu/arcgis1/rest/services/ngds/KS_SURFACE_GEOLOGY/MapServer

http://services.kgs.ku.edu/arcgis1/rest/services/ngds/KSBoreholeTemperatures/MapServer

http://services.kgs.ku.edu/arcgis1/rest/services/ngds/KSWellHeaders/MapServer

http://services.kgs.ku.edu/arcgis1/rest/services/ngds/KSWellLogs/MapServer

http://services.kgs.ku.edu/arcgis1/rest/services/ngds/KSWellTests/MapServer

**Comment by smrazgs** [comment]
Can you update the metadata in the catalog?

**Comment by Lbookman** [comment]
yes. I was just writing it down to update the backlog.

**Comment by Lbookman** [comment]
updated the metadata with the new links. http://services.kgs.ku.edu/arcgis1/rest/services/ngds/
